### ISSUE TITLE
NetCDF file with mismatched dimensions depending on NetCDF version

### ISSUE THREAD

**Issue by jdemaria** [Unidata/netcdf-c#1819]
Hi,

We have a NetCDF file which works fine with v4.2 (HDF5 v1.8.9) with header starting with:
```
dimensions:
	modules = 5 ;
	bands = 21 ;
	module_pixels = 740 ;
	VAM_prog_gains = 8 ;

group: transmission {
  dimensions:
  	T1_wavelengths = 42 ;
  	T2_wavelengths = 18 ;
  	TU_wavelengths = 42 ;
  	TU_kFOV = 9 ;
  variables:
  	double T1_wavelengths(T1_wavelengths) ;
```
For an unknown reason when we tried to update to v4.7.4 (HDF5 v1.10.6) the same ncdump shows mismatched dimensions with the 4 global dimensions "replaced" by the 4 of the first group:
```
dimensions:
	T1_wavelengths = 42 ;
	T2_wavelengths = 18 ;
	TU_wavelengths = 42 ;
	TU_kFOV = 9 ;

group: transmission {
  dimensions:
  	T1_wavelengths = 42 ;
  	T2_wavelengths = 18 ;
  	TU_wavelengths = 42 ;
  	TU_kFOV = 9 ;
  variables:
  	double T1_wavelengths(T1_wavelengths) ;
```
and then ncdump raise an error for the first variable using one of the global dimensions:
```
NetCDF: Invalid dimension ID or name
Location: file ncdump.c; line 1770
```
We tried also to read the file using the Python wrapper and it failed not the same way: when we try to read a variable depending on "modules" dimension we got the error "Start+count exceeds dimension bound" because it seems it found the dimension but the size is 42 instead 5..., example:
```
group: CCD_spectral_responsivity {
  dimensions:
  	wavelengths = 23 ;
  	CCD_lines_useful = 530 ;
  variables:
  	double wavelengths(wavelengths) ;
  	double spectral_responsivity(modules, wavelengths) ;
```
```
import netCDF4 as nc
d = nc.Dataset('****.nc')
>>> v = d.groups['CCD_spectral_responsivity'].variables['spectral_responsivity']
>>> v[:]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "netCDF4/_netCDF4.pyx", line 4452, in netCDF4._netCDF4.Variable.__getitem__
  File "netCDF4/_netCDF4.pyx", line 5394, in netCDF4._netCDF4.Variable._get
  File "netCDF4/_netCDF4.pyx", line 1928, in netCDF4._netCDF4._ensure_nc_success
RuntimeError: NetCDF: Start+count exceeds dimension bound
>>> v.shape
(42, 23)
```

We found a workaround: with v4.2 we can nccopy or ncdump -s -p 9,17 |ncgen and the output file works wellwith v4.7.4... We tried also to compare files before and after and they seem identical, but we are at the point where we have doubts: do we have the real right values in the file or is it possible that data is also mismatched?
Unfortunately this file was created a long time ago and updated several times with different tools (mix of Python, IDL and ncdump|ncgen) and we are not able to re-create it from scratch.
We found that the file version of 2016 don't have the bug.

Can we share in private the file? (please do not distribute it)

Many thanks in advance,
Julien

**Comment by WardF** [comment]
@jdemaria Yes, if you email support-netcdf@unidata.ucar.edu, I will respond directly and we can coordinate a good way to privately share the file. Thank you!

**Comment by jdemaria** [comment]
I just directly emailed you because it seems smtp.unidata.ucar.edu blocks my emails. I shared the file with our OneDrive.
Thanks!
