### ISSUE TITLE
detected memory leaks

### ISSUE THREAD

**Issue by cniddodi** [Unidata/netcdf-c#2669]
detected memory leaks

Built from git commit hash 63150df
OS: Ubuntu 20.04
Compiler: clang version 11.0

Build options:
- Shared library disabled
CC=clang
CXX=clang++
CFLAGS="-g -fno-inline -fsanitize=address"
CXXFLAGS="-g -fno-inline -fsanitize=address"
LDFLAGS="$LDFLAGS -fsanitize=address"
ASAN_OPTIONS=abort_on_error=1

Command: ./ncdump pov

POV file:
[pov.zip](https://github.com/Unidata/netcdf-c/files/11013365/pov.zip)

Stack trace:
```
==3252494==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 56 byte(s) in 1 object(s) allocated from:
#0 0x4c4f4f in malloc /home/chaitra/aflgo-top/build/llvm_tools/llvm-11.0.0.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
#1 0x7fcff8a3a641  (/lib/x86_64-linux-gnu/libhdf5_serial.so.103+0x10a641)
SUMMARY: AddressSanitizer: 56 byte(s) leaked in 1 allocation(s).
```

**Comment by WardF** [comment]
Hello,

Can you provide a description of the POV file you are attaching to these tests?  I also appreciate you are opening issues for clang-detected issues.  We are a relatively small team, and always welcome pull requests to address specific issues as you find them.  Otherwise, I may end up collating the multiple issues reported by clang into a single issue, otherwise we risk having a lot of issues drowning out more specific, addressable, high priority issues.

Thanks!

**Comment by WardF** [comment]
They are not specific to clang, but if we were to enumerage all warnings and errors detected via static analysis, we would find it difficult to triage other, observed issues.  

Can you provide more information about the fuzzer generating the file, how it is generating, what it should look like, the contents, etc?

**Comment by cniddodi** [comment]
I didn't use static analysis to find the errors. Each error report includes an actual input that can demonstrate the observed issue. The attached input files (pov.zip) are sufficient to reproduce the reported errors.
For example, for this error report, one can reproduce the issue on the netcdf version 4.9.1 (git commit hash 63150df) by running the following  command:
`./ncdump pov`

POV file:
[pov.zip](https://github.com/Unidata/netcdf-c/files/11013365/pov.zip)

**Comment by charmoniumQ** [comment]
This should actually be filled as a bug in HDF5, a library that NetCDF includes.

To get a full (but slow) stacktrace, you have to disable fast (but incomplete) unwind:
```
$ ASAN_OPTIONS=fast_unwind_on_malloc=0 ncdump pov
=================================================================
==3123281==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x7fca274c57cf in __interceptor_malloc (/nix/store/8dn12i3d7harw8g7dzk6dy7c5diz5ibp-gcc-11.3.0-lib/lib/libasan.so.6+0xb17cf)
    #1 0x7fca268ab879 in H5FL__malloc /build/hdf5-1.12.1/src/H5FL.c:246
    #2 0x7fca268ac7a6 in H5FL_blk_malloc /build/hdf5-1.12.1/src/H5FL.c:891
    #3 0x7fca269f71b7 in H5O__add_cont_msg /build/hdf5-1.12.1/src/H5Ocache.c:1077
    #4 0x7fca269f8170 in H5O__chunk_deserialize /build/hdf5-1.12.1/src/H5Ocache.c:1518
    #5 0x7fca269f9300 in H5O__cache_deserialize /build/hdf5-1.12.1/src/H5Ocache.c:336
    #6 0x7fca267012bc in H5C__load_entry /build/hdf5-1.12.1/src/H5C.c:7295
    #7 0x7fca267181e5 in H5C_protect /build/hdf5-1.12.1/src/H5C.c:2363
    #8 0x7fca266b79fb in H5AC_protect /build/hdf5-1.12.1/src/H5AC.c:1425
    #9 0x7fca26a2ed70 in H5O_protect /build/hdf5-1.12.1/src/H5Oint.c:1050
    #10 0x7fca26a31208 in H5O_obj_type /build/hdf5-1.12.1/src/H5Oint.c:1650
    #11 0x7fca268e8a7c in H5G__open_name /build/hdf5-1.12.1/src/H5Gint.c:274
    #12 0x7fca26d5be52 in H5VL__native_group_open /build/hdf5-1.12.1/src/H5VLnative_group.c:122
    #13 0x7fca26d1d85c in H5VL__group_open /build/hdf5-1.12.1/src/H5VLcallback.c:4153
    #14 0x7fca26d3161d in H5VL_group_open /build/hdf5-1.12.1/src/H5VLcallback.c:4185
    #15 0x7fca268c7857 in H5Gopen2 /build/hdf5-1.12.1/src/H5G.c:508
    #16 0x7fca27206884 in rec_read_metadata /build/netcdf-c-4.8.1/libhdf5/hdf5open.c:2709
    #17 0x7fca2720eafd in nc4_open_file /build/netcdf-c-4.8.1/libhdf5/hdf5open.c:907
    #18 0x7fca2714e3b4 in NC_open /build/netcdf-c-4.8.1/libdispatch/dfile.c:2128
    #19 0x7fca2714e6c3 in nc_open /build/netcdf-c-4.8.1/libdispatch/dfile.c:657
    #20 0x4042e4 in main /build/netcdf-c-4.8.1/ncdump/ncdump.c:2423
    #21 0x7fca2613c236 in __libc_start_call_main (/nix/store/fz33c1mfi2krpg1lwzizfw28kj705yg0-glibc-2.34-210/lib/libc.so.6+0x29236)
    #22 0x7fca2613c2f4 in __libc_start_main_impl (/nix/store/fz33c1mfi2krpg1lwzizfw28kj705yg0-glibc-2.34-210/lib/libc.so.6+0x292f4)
    #23 0x404800 in _start (/nix/store/chliz97wjsj8yy2ipnlqyf1qy7qny11a-netcdf-4.8.1/bin/ncdump+0x404800)

SUMMARY: AddressSanitizer: 56 byte(s) leaked in 1 allocation(s).
```

and then we see that most of the error comes from `/build/hdf5-1.12.1/`.

Indeed, we can reproduce this error with more details by removing NetCDF from the equation entirely:
```
$ ASAN_OPTIONS=fast_unwind_on_malloc=0 h5dump pov
h5dump error: internal error (file h5dump.c:line 1550)
HDF5: infinite loop closing library
      L,T_top,P,P,FD,VL,VL,E,SL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL

=================================================================
==3123345==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x7f4774d0b7cf in __interceptor_malloc (/nix/store/8dn12i3d7harw8g7dzk6dy7c5diz5ibp-gcc-11.3.0-lib/lib/libasan.so.6+0xb17cf)
    #1 0x7f477447e879 in H5FL__malloc /build/hdf5-1.12.1/src/H5FL.c:246
    #2 0x7f477447f7a6 in H5FL_blk_malloc /build/hdf5-1.12.1/src/H5FL.c:891
    #3 0x7f47745ca1b7 in H5O__add_cont_msg /build/hdf5-1.12.1/src/H5Ocache.c:1077
    #4 0x7f47745cb170 in H5O__chunk_deserialize /build/hdf5-1.12.1/src/H5Ocache.c:1518
    #5 0x7f47745cc300 in H5O__cache_deserialize /build/hdf5-1.12.1/src/H5Ocache.c:336
    #6 0x7f47742d42bc in H5C__load_entry /build/hdf5-1.12.1/src/H5C.c:7295
    #7 0x7f47742eb1e5 in H5C_protect /build/hdf5-1.12.1/src/H5C.c:2363
    #8 0x7f477428a9fb in H5AC_protect /build/hdf5-1.12.1/src/H5AC.c:1425
    #9 0x7f4774601d70 in H5O_protect /build/hdf5-1.12.1/src/H5Oint.c:1050
    #10 0x7f4774606994 in H5O_get_info /build/hdf5-1.12.1/src/H5Oint.c:2193
    #11 0x7f47744c16ad in H5G__loc_info_cb /build/hdf5-1.12.1/src/H5Gloc.c:772
    #12 0x7f47744e9b69 in H5G__traverse_real /build/hdf5-1.12.1/src/H5Gtraverse.c:753
    #13 0x7f47744ebbed in H5G_traverse /build/hdf5-1.12.1/src/H5Gtraverse.c:836
    #14 0x7f47744c5749 in H5G_loc_info /build/hdf5-1.12.1/src/H5Gloc.c:814
    #15 0x7f4774935272 in H5VL__native_object_get /build/hdf5-1.12.1/src/H5VLnative_object.c:247
    #16 0x7f47748f2053 in H5VL__object_get /build/hdf5-1.12.1/src/H5VLcallback.c:5565
    #17 0x7f477490a5c9 in H5VL_object_get /build/hdf5-1.12.1/src/H5VLcallback.c:5601
    #18 0x7f4774594ffb in H5Oget_info_by_name3 /build/hdf5-1.12.1/src/H5O.c:604
    #19 0x4075b9  (/nix/store/h1rnsfly3xkf9w1b7dwpjwvpdaivkm62-hdf5-1.12.1/bin/h5dump+0x4075b9)
    #20 0x7f4773dac236 in __libc_start_call_main (/nix/store/fz33c1mfi2krpg1lwzizfw28kj705yg0-glibc-2.34-210/lib/libc.so.6+0x29236)
    #21 0x7f4773dac2f4 in __libc_start_main_impl (/nix/store/fz33c1mfi2krpg1lwzizfw28kj705yg0-glibc-2.34-210/lib/libc.so.6+0x292f4)
    #22 0x408930  (/nix/store/h1rnsfly3xkf9w1b7dwpjwvpdaivkm62-hdf5-1.12.1/bin/h5dump+0x408930)

Direct leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f4774d0b7cf in __interceptor_malloc (/nix/store/8dn12i3d7harw8g7dzk6dy7c5diz5ibp-gcc-11.3.0-lib/lib/libasan.so.6+0xb17cf)
    #1 0x45d523  (/nix/store/h1rnsfly3xkf9w1b7dwpjwvpdaivkm62-hdf5-1.12.1/bin/h5dump+0x45d523)
    #2 0x45f30a  (/nix/store/h1rnsfly3xkf9w1b7dwpjwvpdaivkm62-hdf5-1.12.1/bin/h5dump+0x45f30a)
    #3 0x40cf21  (/nix/store/h1rnsfly3xkf9w1b7dwpjwvpdaivkm62-hdf5-1.12.1/bin/h5dump+0x40cf21)
    #4 0x4075e7  (/nix/store/h1rnsfly3xkf9w1b7dwpjwvpdaivkm62-hdf5-1.12.1/bin/h5dump+0x4075e7)
    #5 0x7f4773dac236 in __libc_start_call_main (/nix/store/fz33c1mfi2krpg1lwzizfw28kj705yg0-glibc-2.34-210/lib/libc.so.6+0x29236)
    #6 0x7f4773dac2f4 in __libc_start_main_impl (/nix/store/fz33c1mfi2krpg1lwzizfw28kj705yg0-glibc-2.34-210/lib/libc.so.6+0x292f4)
    #7 0x408930  (/nix/store/h1rnsfly3xkf9w1b7dwpjwvpdaivkm62-hdf5-1.12.1/bin/h5dump+0x408930)

Direct leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f4774d0b7cf in __interceptor_malloc (/nix/store/8dn12i3d7harw8g7dzk6dy7c5diz5ibp-gcc-11.3.0-lib/lib/libasan.so.6+0xb17cf)
    #1 0x45d523  (/nix/store/h1rnsfly3xkf9w1b7dwpjwvpdaivkm62-hdf5-1.12.1/bin/h5dump+0x45d523)
    #2 0x45f2ff  (/nix/store/h1rnsfly3xkf9w1b7dwpjwvpdaivkm62-hdf5-1.12.1/bin/h5dump+0x45f2ff)
    #3 0x40cf21  (/nix/store/h1rnsfly3xkf9w1b7dwpjwvpdaivkm62-hdf5-1.12.1/bin/h5dump+0x40cf21)
    #4 0x4075e7  (/nix/store/h1rnsfly3xkf9w1b7dwpjwvpdaivkm62-hdf5-1.12.1/bin/h5dump+0x4075e7)
    #5 0x7f4773dac236 in __libc_start_call_main (/nix/store/fz33c1mfi2krpg1lwzizfw28kj705yg0-glibc-2.34-210/lib/libc.so.6+0x29236)
    #6 0x7f4773dac2f4 in __libc_start_main_impl (/nix/store/fz33c1mfi2krpg1lwzizfw28kj705yg0-glibc-2.34-210/lib/libc.so.6+0x292f4)
    #7 0x408930  (/nix/store/h1rnsfly3xkf9w1b7dwpjwvpdaivkm62-hdf5-1.12.1/bin/h5dump+0x408930)

Direct leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f4774d0b7cf in __interceptor_malloc (/nix/store/8dn12i3d7harw8g7dzk6dy7c5diz5ibp-gcc-11.3.0-lib/lib/libasan.so.6+0xb17cf)
    #1 0x45d523  (/nix/store/h1rnsfly3xkf9w1b7dwpjwvpdaivkm62-hdf5-1.12.1/bin/h5dump+0x45d523)
    #2 0x45f2f4  (/nix/store/h1rnsfly3xkf9w1b7dwpjwvpdaivkm62-hdf5-1.12.1/bin/h5dump+0x45f2f4)
    #3 0x40cf21  (/nix/store/h1rnsfly3xkf9w1b7dwpjwvpdaivkm62-hdf5-1.12.1/bin/h5dump+0x40cf21)
    #4 0x4075e7  (/nix/store/h1rnsfly3xkf9w1b7dwpjwvpdaivkm62-hdf5-1.12.1/bin/h5dump+0x4075e7)
    #5 0x7f4773dac236 in __libc_start_call_main (/nix/store/fz33c1mfi2krpg1lwzizfw28kj705yg0-glibc-2.34-210/lib/libc.so.6+0x29236)
    #6 0x7f4773dac2f4 in __libc_start_main_impl (/nix/store/fz33c1mfi2krpg1lwzizfw28kj705yg0-glibc-2.34-210/lib/libc.so.6+0x292f4)
    #7 0x408930  (/nix/store/h1rnsfly3xkf9w1b7dwpjwvpdaivkm62-hdf5-1.12.1/bin/h5dump+0x408930)

SUMMARY: AddressSanitizer: 152 byte(s) leaked in 4 allocation(s).
```
