### ISSUE TITLE
memory leak in tst_enums is real library leak, and somewhat challenging

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#517]
There is a memory leak revealed by tst_enums. This turns out not to be just a test artifact, but reveals a possible memory leak in the library. Analysis below...

```
ed@mikado:~/tmp/netcdf-c/nc_test4$ ./tst_enums 

*** Testing netcdf-4 enum type.
*** testing creation of enum type...ok.
*** testing enum attribute...ok.
*** testing enum fill value ...ok.
*** testing enum interuptus...ok.
*** Tests successful!

=================================================================
==27054==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 524 byte(s) in 1 object(s) allocated from:
    #0 0x7f2786494080 in calloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc7080)
    #1 0x7f27830e2ef0 in NC4_get_fileinfo /home/ed/tmp/netcdf-c/libsrc4/nc4info.c:190
    #2 0x7f27830a86b4 in nc4_create_file /home/ed/tmp/netcdf-c/libsrc4/nc4file.c:538
    #3 0x7f27830a893c in NC4_create /home/ed/tmp/netcdf-c/libsrc4/nc4file.c:635
    #4 0x7f2782f32534 in NC_create /home/ed/tmp/netcdf-c/libdispatch/dfile.c:1788
    #5 0x7f2782f305ce in nc__create /home/ed/tmp/netcdf-c/libdispatch/dfile.c:515
    #6 0x7f2782f30587 in nc_create /home/ed/tmp/netcdf-c/libdispatch/dfile.c:444
    #7 0x55e416a23350 in main /home/ed/tmp/netcdf-c/nc_test4/tst_enums.c:290
    #8 0x7f27829013f0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x203f0)

Direct leak of 120 byte(s) in 1 object(s) allocated from:
    #0 0x7f2786494080 in calloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc7080)
    #1 0x7f27830d246c in nc4_grp_list_add /home/ed/tmp/netcdf-c/libsrc4/nc4internal.c:750
    #2 0x7f27830cfb2a in nc4_nc4f_list_add /home/ed/tmp/netcdf-c/libsrc4/nc4internal.c:219
    #3 0x7f27830a81bd in nc4_create_file /home/ed/tmp/netcdf-c/libsrc4/nc4file.c:408
    #4 0x7f27830a893c in NC4_create /home/ed/tmp/netcdf-c/libsrc4/nc4file.c:635
    #5 0x7f2782f32534 in NC_create /home/ed/tmp/netcdf-c/libdispatch/dfile.c:1788
    #6 0x7f2782f305ce in nc__create /home/ed/tmp/netcdf-c/libdispatch/dfile.c:515
    #7 0x7f2782f30587 in nc_create /home/ed/tmp/netcdf-c/libdispatch/dfile.c:444
    #8 0x55e416a23350 in main /home/ed/tmp/netcdf-c/nc_test4/tst_enums.c:290
    #9 0x7f27829013f0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x203f0)

Indirect leak of 104 byte(s) in 1 object(s) allocated from:
    #0 0x7f2786494080 in calloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc7080)
    #1 0x7f27830d28ee in nc4_type_list_add /home/ed/tmp/netcdf-c/libsrc4/nc4internal.c:816
    #2 0x7f27830d65ac in add_user_type /home/ed/tmp/netcdf-c/libsrc4/nc4type.c:230
    #3 0x7f27830d85df in NC4_def_enum /home/ed/tmp/netcdf-c/libsrc4/nc4type.c:559
    #4 0x7f2782f67939 in nc_def_enum /home/ed/tmp/netcdf-c/libdispatch/denum.c:48
    #5 0x55e416a23412 in main /home/ed/tmp/netcdf-c/nc_test4/tst_enums.c:293
    #6 0x7f27829013f0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x203f0)

Indirect leak of 10 byte(s) in 1 object(s) allocated from:
    #0 0x7f27864271c0 in __interceptor_strdup (/usr/lib/x86_64-linux-gnu/libasan.so.3+0x5a1c0)
    #1 0x7f27830d29fa in nc4_type_list_add /home/ed/tmp/netcdf-c/libsrc4/nc4internal.c:825
    #2 0x7f27830d65ac in add_user_type /home/ed/tmp/netcdf-c/libsrc4/nc4type.c:230
    #3 0x7f27830d85df in NC4_def_enum /home/ed/tmp/netcdf-c/libsrc4/nc4type.c:559
    #4 0x7f2782f67939 in nc_def_enum /home/ed/tmp/netcdf-c/libdispatch/denum.c:48
    #5 0x55e416a23412 in main /home/ed/tmp/netcdf-c/nc_test4/tst_enums.c:293
    #6 0x7f27829013f0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x203f0)

Indirect leak of 2 byte(s) in 1 object(s) allocated from:
    #0 0x7f27864271c0 in __interceptor_strdup (/usr/lib/x86_64-linux-gnu/libasan.so.3+0x5a1c0)
    #1 0x7f27830d24fb in nc4_grp_list_add /home/ed/tmp/netcdf-c/libsrc4/nc4internal.c:756
    #2 0x7f27830cfb2a in nc4_nc4f_list_add /home/ed/tmp/netcdf-c/libsrc4/nc4internal.c:219
    #3 0x7f27830a81bd in nc4_create_file /home/ed/tmp/netcdf-c/libsrc4/nc4file.c:408
    #4 0x7f27830a893c in NC4_create /home/ed/tmp/netcdf-c/libsrc4/nc4file.c:635
    #5 0x7f2782f32534 in NC_create /home/ed/tmp/netcdf-c/libdispatch/dfile.c:1788
    #6 0x7f2782f305ce in nc__create /home/ed/tmp/netcdf-c/libdispatch/dfile.c:515
    #7 0x7f2782f30587 in nc_create /home/ed/tmp/netcdf-c/libdispatch/dfile.c:444
    #8 0x55e416a23350 in main /home/ed/tmp/netcdf-c/nc_test4/tst_enums.c:290
    #9 0x7f27829013f0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x203f0)

SUMMARY: AddressSanitizer: 760 byte(s) leaked in 5 allocation(s).
```

What is happening here is the following test code, which creates an enum, and then closes the file without saving the type. As expected, the test gets an NC_EINVAL on the nc_close(), but some memory is left unfreed:

```
   printf("*** testing enum interuptus...");
   {
#define GEEKY_NAME "Galadriel"

      /* Create a file. */
      if (nc_create(FILE_NAME, NC_NETCDF4, &ncid)) ERR;

      /* Create an enum type based on unsigned bytes. */
      if (nc_def_enum(ncid, NC_UBYTE, GEEKY_NAME, &typeid)) ERR;

      /* Check it out. */
      if (nc_inq_user_type(ncid, typeid, name_in, &base_size_in, &base_nc_type_in,
			   &nfields_in, &class_in)) ERR;
      if (strcmp(name_in, GEEKY_NAME) || base_size_in != 1 ||
	  base_nc_type_in != NC_UBYTE || nfields_in != 0 || class_in != NC_ENUM) ERR;
      if (nc_inq_enum(ncid, typeid, name_in, &base_nc_type, &base_size_in, &num_members)) ERR;
      if (strcmp(name_in, GEEKY_NAME) || base_nc_type != NC_UBYTE || base_size_in != 1 ||
	  num_members != 0) ERR;

      /* Close the file. */
      if (nc_close(ncid) != NC_EINVAL) ERR;

   }

```

 The problem is that things have been added to the type list as the test code creates an enum type. This memory is never freed.

I was hoping that I could just finish things off like this:
```
      unsigned char ubyte_value = 42;
      if (nc_redef(ncid)) ERR;
      if (nc_insert_enum(ncid, NC_UBYTE, "name", &ubyte_value)) ERR;
      if (nc_close(ncid)) ERR;

```

But the nc_close(), while failing, still manages to make ncid unusable.

I guess the proper answer is that nc_close should check that it can close a file before doing anything else. If it can't close the file, it should return an error code and ncid should remain valid for other operations.

Ward and Denis, any thoughts on this one?

**Comment by edhartnett** [comment]
OK, I have a fix for this, which causes the library to not delete anything if the close fails. So then I can add on the extra code above to finish off the enum and properly close the file. Now there are no leaks. I will put the PR up shortly.

**Comment by edhartnett** [comment]
This is now up as PR #559.
