### ISSUE TITLE
memory issues in ncgen

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#549]
Some memory issues in ncgen, as can be seen with address sanitizer.

Build on linux like this:

`make distclean && autoreconf -i && CPPFLAGS='-I/usr/local/zlib-1.2.11/include -I/usr/local/szip-2.1/include -I/usr/local/hdf5-1.10.1_memchecker/include' CFLAGS='-g -Wall -fsanitize=address -fno-omit-frame-pointer' LDFLAGS='-L/usr/local/zlib-1.2.11/lib -L/usr/local/szip-2.1/lib -L/usr/local/hdf5-1.10.1_memchecker/lib' ./configure && make all check 
`
The following is from the run of nc_test/run_diskless5.sh, which starts by calling ncgen.

```
+ /home/ed/tmp/netcdf-c/ncgen/ncgen -3 -lb -o tst_diskless5.nc /home/ed/tmp/netcdf-c/nc_test/tst_diskless5.cdl

=================================================================
==28474==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 256 byte(s) in 1 object(s) allocated from:
    #0 0x7f50fce10080 in calloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc7080)
    #1 0x55edcdf9ef39 in chkmalloc /home/ed/tmp/netcdf-c/ncgen/debug.c:39
    #2 0x55edcdf91e83 in main /home/ed/tmp/netcdf-c/ncgen/main.c:485
    #3 0x7f50f8cb73f0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x203f0)

Direct leak of 120 byte(s) in 5 object(s) allocated from:
    #0 0x7f50fce10080 in calloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc7080)
    #1 0x55edcdf9ef39 in chkmalloc /home/ed/tmp/netcdf-c/ncgen/debug.c:39
    #2 0x55edcdfbecc1 in bbNew /home/ed/tmp/netcdf-c/ncgen/bytebuffer.c:38
    #3 0x55edcdfad1bb in genbin_definevardata /home/ed/tmp/netcdf-c/ncgen/genbin.c:368
    #4 0x55edcdfab6c1 in gen_netcdf /home/ed/tmp/netcdf-c/ncgen/genbin.c:171
    #5 0x55edcdfaf596 in define_netcdf /home/ed/tmp/netcdf-c/ncgen/genlib.c:63
    #6 0x55edcdf92283 in main /home/ed/tmp/netcdf-c/ncgen/main.c:582
    #7 0x7f50f8cb73f0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x203f0)

Direct leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7f50fce10080 in calloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc7080)
    #1 0x55edcdf9ef39 in chkmalloc /home/ed/tmp/netcdf-c/ncgen/debug.c:39
    #2 0x55edcdfbecc1 in bbNew /home/ed/tmp/netcdf-c/ncgen/bytebuffer.c:38
    #3 0x55edcdfad0f0 in genbin_defineattr /home/ed/tmp/netcdf-c/ncgen/genbin.c:356
    #4 0x55edcdfab403 in gen_netcdf /home/ed/tmp/netcdf-c/ncgen/genbin.c:151
    #5 0x55edcdfaf596 in define_netcdf /home/ed/tmp/netcdf-c/ncgen/genlib.c:63
    #6 0x55edcdf92283 in main /home/ed/tmp/netcdf-c/ncgen/main.c:582
    #7 0x7f50f8cb73f0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x203f0)

Direct leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7f50fce0fec0 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc6ec0)
    #1 0x55edcdfc059c in listnew /home/ed/tmp/netcdf-c/ncgen/list.c:30
    #2 0x55edcdfb4b82 in processenums /home/ed/tmp/netcdf-c/ncgen/semantics.c:390
    #3 0x55edcdfb28d4 in processsemantics /home/ed/tmp/netcdf-c/ncgen/semantics.c:59
    #4 0x55edcdf92230 in main /home/ed/tmp/netcdf-c/ncgen/main.c:580
    #5 0x7f50f8cb73f0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x203f0)

Direct leak of 2 byte(s) in 1 object(s) allocated from:
    #0 0x7f50fce10080 in calloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc7080)
    #1 0x55edcdf9ef39 in chkmalloc /home/ed/tmp/netcdf-c/ncgen/debug.c:39
    #2 0x55edcdf9157a in main /home/ed/tmp/netcdf-c/ncgen/main.c:300
    #3 0x7f50f8cb73f0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x203f0)

Indirect leak of 1048576 byte(s) in 4 object(s) allocated from:
    #0 0x7f50fce10080 in calloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc7080)
    #1 0x55edcdf9ef39 in chkmalloc /home/ed/tmp/netcdf-c/ncgen/debug.c:39
    #2 0x55edcdf9ef1a in chkcalloc /home/ed/tmp/netcdf-c/ncgen/debug.c:33
    #3 0x55edcdfbeef8 in bbSetalloc /home/ed/tmp/netcdf-c/ncgen/bytebuffer.c:56
    #4 0x55edcdf8d4e9 in generate_vardata /home/ed/tmp/netcdf-c/ncgen/generate.c:93
    #5 0x55edcdfad23c in genbin_definevardata /home/ed/tmp/netcdf-c/ncgen/genbin.c:370
    #6 0x55edcdfab6c1 in gen_netcdf /home/ed/tmp/netcdf-c/ncgen/genbin.c:171
    #7 0x55edcdfaf596 in define_netcdf /home/ed/tmp/netcdf-c/ncgen/genlib.c:63
    #8 0x55edcdf92283 in main /home/ed/tmp/netcdf-c/ncgen/main.c:582
    #9 0x7f50f8cb73f0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x203f0)

Indirect leak of 524288 byte(s) in 1 object(s) allocated from:
    #0 0x7f50fce10080 in calloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc7080)
    #1 0x55edcdf9ef39 in chkmalloc /home/ed/tmp/netcdf-c/ncgen/debug.c:39
    #2 0x55edcdf9ef1a in chkcalloc /home/ed/tmp/netcdf-c/ncgen/debug.c:33
    #3 0x55edcdfbeef8 in bbSetalloc /home/ed/tmp/netcdf-c/ncgen/bytebuffer.c:56
    #4 0x55edcdfbf7ed in bbAppendn /home/ed/tmp/netcdf-c/ncgen/bytebuffer.c:152
    #5 0x55edcdf93c34 in bin_constant /home/ed/tmp/netcdf-c/ncgen/bindata.c:54
    #6 0x55edcdf90ec1 in generate_primdata /home/ed/tmp/netcdf-c/ncgen/generate.c:541
    #7 0x55edcdf8ecdf in generate_basetype /home/ed/tmp/netcdf-c/ncgen/generate.c:304
    #8 0x55edcdf8dd36 in generate_array /home/ed/tmp/netcdf-c/ncgen/generate.c:177
    #9 0x55edcdf8d601 in generate_vardata /home/ed/tmp/netcdf-c/ncgen/generate.c:107
    #10 0x55edcdfad23c in genbin_definevardata /home/ed/tmp/netcdf-c/ncgen/genbin.c:370
    #11 0x55edcdfab6c1 in gen_netcdf /home/ed/tmp/netcdf-c/ncgen/genbin.c:171
    #12 0x55edcdfaf596 in define_netcdf /home/ed/tmp/netcdf-c/ncgen/genlib.c:63
    #13 0x55edcdf92283 in main /home/ed/tmp/netcdf-c/ncgen/main.c:582
    #14 0x7f50f8cb73f0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x203f0)

Indirect leak of 1024 byte(s) in 1 object(s) allocated from:
    #0 0x7f50fce10080 in calloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc7080)
    #1 0x55edcdf9ef39 in chkmalloc /home/ed/tmp/netcdf-c/ncgen/debug.c:39
    #2 0x55edcdf9ef1a in chkcalloc /home/ed/tmp/netcdf-c/ncgen/debug.c:33
    #3 0x55edcdfbeef8 in bbSetalloc /home/ed/tmp/netcdf-c/ncgen/bytebuffer.c:56
    #4 0x55edcdfbf7ed in bbAppendn /home/ed/tmp/netcdf-c/ncgen/bytebuffer.c:152
    #5 0x55edcdf94e3d in gen_charconstant /home/ed/tmp/netcdf-c/ncgen/genchar.c:171
    #6 0x55edcdf94b9e in gen_charvlen /home/ed/tmp/netcdf-c/ncgen/genchar.c:145
    #7 0x55edcdf94a3f in gen_charattr /home/ed/tmp/netcdf-c/ncgen/genchar.c:131
    #8 0x55edcdf8d008 in generate_attrdata /home/ed/tmp/netcdf-c/ncgen/generate.c:62
    #9 0x55edcdfad171 in genbin_defineattr /home/ed/tmp/netcdf-c/ncgen/genbin.c:358
    #10 0x55edcdfab403 in gen_netcdf /home/ed/tmp/netcdf-c/ncgen/genbin.c:151
    #11 0x55edcdfaf596 in define_netcdf /home/ed/tmp/netcdf-c/ncgen/genlib.c:63
    #12 0x55edcdf92283 in main /home/ed/tmp/netcdf-c/ncgen/main.c:582
    #13 0x7f50f8cb73f0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x203f0)

SUMMARY: AddressSanitizer: 1574314 byte(s) leaked in 15 allocation(s).
```

**Comment by edhartnett** [comment]
I am looking at the code and starting to come to the horrific conclusion that it was just written to not free memory. That is, the code does not even seem to try to free any of the memory it allocates. Could that be correct?

**Comment by DennisHeimbigner** [comment]
Sure, After all, the memory it allocates is needed almost to the end of execution. Since it is a standalone
program, why bother trying to reclaim it.

**Comment by edhartnett** [comment]
OK I will close this ticket. For my memory checking builds I can --disable-utilities and avoid this problem.
