### ISSUE TITLE
Memory error in new test nc_test4/tst_filterparser

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#645]
There is a memory error identified by the address sanitizer in nc_test4/tst_filterparser. @DennisHeimbigner I believe this is a test just added by you.

I will take a look and see if this is an easy fix.

This is a real bummer because I just got the address sanitizer working for --disable-dap and --disable-utilities. Not it breaks again in my CI.

@Ward it would be great if you could add a travis test to ensure that memory leaks are not merged into master.

**Comment by edhartnett** [comment]
The funny thing is, this happens in my Jenkins build, but not from the command line. Not sure why yet.

Here's the error message from address sanitizer:

```
=================================================================
==1974==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 104 byte(s) in 1 object(s) allocated from:
    #0 0x7f42e4da9b50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
    #1 0x7f42e495a0b8 in NC_parsefilterspec /var/lib/jenkins/workspace/WDC_ejh_netcdf-c_hdf5_1.10.1_no_dap_no_utilities_asan/libdispatch/dfilter.c:76
    #2 0x55ba86b84570 in main /var/lib/jenkins/workspace/WDC_ejh_netcdf-c_hdf5_1.10.1_no_dap_no_utilities_asan/nc_test4/tst_filterparser.c:92
    #3 0x7f42e451b1c0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x211c0)

SUMMARY: AddressSanitizer: 104 byte(s) leaked in 1 allocation(s).
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

When I look at the code, I see this:

EXTERNL int
```
NC_parsefilterspec(const char* spec, unsigned int* idp, size_t* nparamsp, unsigned int** paramsp)
{
    char* p;
    char* sdata = NULL;
    int stat;
    unsigned int id;
    size_t count; /* no. of comma delimited params */
    size_t nparams; /* final no. of unsigned ints */
    size_t i;
    unsigned int* ulist = NULL;
    unsigned char mem[8]; /* to convert to network byte order */

    if(spec == NULL || strlen(spec) == 0) goto fail;
    sdata = strdup(spec);

    /* Count number of parameters + id and delimit */
    p=sdata;
    for(count=0;;count++) {
        char* q = strchr(p,',');
	if(q == NULL) break;
	*q++ = '\0';
	p = q;
    }
    count++; /* for final piece */

    if(count == 0)
	goto fail; /* no id and no parameters */

    /* Extract the filter id */
    p = sdata;
    stat = sscanf(p,"%u",&id);
    if(stat != 1) goto fail;
    p = p + strlen(p) + 1; /* skip the filter id */
    count--;

    /* Allocate the max needed space; *2 in case the params are all doubles */
    ulist = (unsigned int*)malloc(sizeof(unsigned int)*(count)*2);
    if(ulist == NULL) goto fail;

    /* walk and convert */
    nparams = 0;
    for(i=0;i<count;i++) {
	char* q;
	unsigned long long val64u;
	unsigned int val32u;
	double vald;
	float valf;
	unsigned int *vector;
	int isunsigned;
	int isnegative;
	int type;

	/* Get trailing discrimination characters */
	isunsigned = 0;
	isnegative = 0;
        type = 0;
	if(strchr(p,'-') != NULL) isnegative = 1;
        q = p+strlen(p)-2;
	if(*q == 'U' || *q == 'u') isunsigned = 1;
	q++;
	switch (*q) {
	case 'f': case 'F': type = 'f'; break; /* short */
	case 'd': case 'D': type = 'd'; break; /* double */
	case 'b': case 'B': type = 'b'; break; /* byte */
	case 's': case 'S': type = 's'; break; /* short */
	case 'l': case 'L': type = 'l'; break; /* long long */
	case 'u': case 'U': type = 'i'; isunsigned = 1; break; /* integer */
	case '.':
	case '0': case '1': case '2': case '3': case '4':
	case '5': case '6': case '7': case '8': case '9': type = 'i'; break;
	default:
	    if(*q == '\0')
		type = 'i';
	    else goto fail;
	}
	/* Now parse */
	switch (type) {
	case 'b':
	case 's':
	case 'i':
 	    /* special case for a positive integer;for back compatibility.*/
	    if(!isnegative)
	        stat = sscanf(p,"%u",&val32u);
	    else
                stat = sscanf(p,"%d",(int*)&val32u);
	    if(stat != 1) goto fail;
	    ulist[nparams++] = val32u;
	    break;
	case 'f':
	    stat = sscanf(p,"%lf",&vald);
	    if(stat != 1) goto fail;
	    valf = (float)vald;
	    ulist[nparams++] = *(unsigned int*)&valf;
	    break;
	case 'd':
	    stat = sscanf(p,"%lf",&vald);
	    if(stat != 1) goto fail;
	    /* convert to network byte order */
	    memcpy(mem,&vald,sizeof(mem));
#ifdef WORDS_BIGENDIAN
	    byteswap8(mem);  /* convert big endian to little endian */
#endif
	    vector = (unsigned int*)mem;
	    ulist[nparams++] = vector[0];
	    ulist[nparams++] = vector[1];
	    break;
	case 'l': /* long long */
	    if(isunsigned)
	        stat = sscanf(p,"%llu",&val64u);
	    else
                stat = sscanf(p,"%lld",(long long*)&val64u);
	    if(stat != 1) goto fail;
	    /* convert to network byte order */
	    memcpy(mem,&val64u,sizeof(mem));
#ifdef WORDS_BIGENDIAN	    
	    byteswap8(mem);  /* convert big endian to little endian */
#endif
	    vector = (unsigned int*)mem;
	    ulist[nparams++] = vector[0];
	    ulist[nparams++] = vector[1];
	    break;
	default:
	    goto fail;
	}
        p = p + strlen(p) + 1; /* move to next param */
    }
    /* Now return results */
    if(idp) *idp = id;
    if(nparamsp) *nparamsp = nparams;
    if(paramsp) *paramsp = ulist;
    ulist = NULL; /* avoid duplicate free */
    if(sdata) free(sdata);
    if(ulist) free(ulist);
    return 1;
fail:
    if(sdata) free(sdata);
    if(ulist) free(ulist);
    return 0;
}

```

Looking at the code, I suspect the problem is ` ulist = NULL; /* avoid duplicate free */`. Looks like this line should be included in the if statement above, but is not. 

However, that execution path is not tested. The test does provide a params pointer.

Turns out the problem is in the test. The params poitner needs to be freed. I will have a PR up shortly.

**Comment by edhartnett** [comment]
I have PR #649 up with a fix.

@DennisHeimbigner calling this function with a NULL paramsp parameter will cause a leak as well. Should I fix that too? I guess I better...

**Comment by DennisHeimbigner** [comment]
You are correct, this is wrong:
> if(paramsp) *paramsp = ulist;
> ulist = NULL; /* avoid duplicate free */

**Comment by edhartnett** [comment]
I fixed it in the PR.
