### ISSUE TITLE
nc_test4/tst_vars2 fails on OSX

### ISSUE THREAD

**Issue by WardF** [Unidata/netcdf-c#861]
Seeing a crash on OSX but not Windows or linux for tst_vars2.  Debugging.

**Comment by WardF** [comment]
@edhartnett  The first commit that fails is e0577cb2.  Output is 

````{.bash}
(....)
*** Testing with HDF5, netCDF Classic Model:
**** testing simple fill value attribute creation...ok.
**** testing simple fill value with data read...ok.
**** testing fill value with one other attribute...ok.
**** testing fill value with three other attributes...ok.
**** testing fill value with simple example...ok.
**** testing fill value with example from cxx tests in v2 api...ok.
**** testing create order varids...ok.
**** testing simple variable renaming...ok.
**** testing dimension and variable renaming...ok.
*** testing 2D array of NC_FLOAT with v2 API...ok.
**** testing funny names for netCDF-4...ok.
**** testing endianness...ok.
**** testing chunking and the chunk cache...ok.
**** testing netCDF-4 functions on netCDF-3 files...ok.
**** testing contiguous storage...ok.
**** testing extreme numbers dude...ok.
**** testing error codes for name clashes...ok.
**** testing error codes for name clashes some more...ok.
**** testing error codes for name clashes even more...ok.
**** testing error code for too-large chunks...ok.
**** testing that contiguous storage can't be turned on for vars with unlimited dims or filters...ok.
**** testing error conditions on nc_def_var functions...ok.
**** testing that contiguous storage can't be turned on for vars with unlimited dims or filters...ok.
**** testing very large chunksizes...ok.
*** Tests successful!
Abort trap: 6 (core dumped)
````

**Comment by WardF** [comment]
Note to self: compiling with address sanitizer, we see the following (sorry it's a bit long). 

```{.bash}
** Testing netcdf-4 variable functions, even more.
*** Testing with classic format:
**** testing simple fill value attribute creation...ok.
**** testing simple fill value with data read...ok.
**** testing fill value with one other attribute...ok.
**** testing fill value with three other attributes...ok.
**** testing fill value with simple example...ok.
**** testing fill value with example from cxx tests in v2 api...ok.
*** Testing with 64-bit offset format:
**** testing simple fill value attribute creation...ok.
**** testing simple fill value with data read...ok.
**** testing fill value with one other attribute...ok.
**** testing fill value with three other attributes...ok.
**** testing fill value with simple example...ok.
**** testing fill value with example from cxx tests in v2 api...ok.
*** Testing with HDF5:
**** testing simple fill value attribute creation...ok.
**** testing simple fill value with data read...ok.
**** testing fill value with one other attribute...ok.
**** testing fill value with three other attributes...ok.
**** testing fill value with simple example...ok.
**** testing fill value with example from cxx tests in v2 api...ok.
*** Testing with HDF5, netCDF Classic Model:
**** testing simple fill value attribute creation...ok.
**** testing simple fill value with data read...ok.
**** testing fill value with one other attribute...ok.
**** testing fill value with three other attributes...ok.
**** testing fill value with simple example...ok.
**** testing fill value with example from cxx tests in v2 api...ok.
**** testing create order varids...ok.
**** testing simple variable renaming...ok.
**** testing dimension and variable renaming...ok.
*** testing 2D array of NC_FLOAT with v2 API...ok.
**** testing funny names for netCDF-4...ok.
**** testing endianness...ok.
=================================================================
==80767==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffee3f2024c at pc 0x00010c15d613 bp 0x7ffee3f1ff50 sp 0x7ffee3f1ff48
WRITE of size 4 at 0x7ffee3f2024c thread T0
    #0 0x10c15d612 in NC4_inq_varids nc4grp.c:499
    #1 0x10c054ee5 in nc_inq_varids dgroup.c:192
    #2 0x10bd002c6 in main tst_vars2.c:962
    #3 0x7fff54e2c114 in start (libdyld.dylib:x86_64+0x1114)

Address 0x7ffee3f2024c is located in stack of thread T0 at offset 108 in frame
    #0 0x10bcd86bf in main tst_vars2.c:26

  This frame has 207 object(s):
    [32, 36) 'ncid' (line 27)
    [48, 52) 'dimids' (line 27)
    [64, 68) 'varid' (line 28)
    [80, 84) 'nvars_in' (line 29)
    [96, 108) 'varids_in' (line 29) <== Memory access at offset 108 overflows this variable
    [128, 129) 'fill_value' (line 30)
````

**Comment by WardF** [comment]
Fixed overflow, now seeing the following:

````{.bash}
*** testing 2D array of NC_FLOAT with v2 API...ok.
**** testing funny names for netCDF-4...ok.
**** testing endianness...ok.
**** testing chunking and the chunk cache...ok.
**** testing netCDF-4 functions on netCDF-3 files...ok.
**** testing contiguous storage...ok.
**** testing extreme numbers dude...ok.
**** testing error codes for name clashes...ok.
**** testing error codes for name clashes some more...ok.
**** testing error codes for name clashes even more...ok.
**** testing error code for too-large chunks...ok.
**** testing that contiguous storage can't be turned on for vars with unlimited dims or filters...ok.
**** testing error conditions on nc_def_var functions...ok.
**** testing that contiguous storage can't be turned on for vars with unlimited dims or filters...ok.
**** testing very large chunksizes...Sorry! Unexpected result, /Users/wfisher/Desktop/t/netcdf-c/nc_test4/tst_vars2.c, line: 1557
````
