### ISSUE TITLE
Memory issues with index.dmh branch

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#917]
As requested by @DennisHeimbigner, here is one github issue for all index.dmh memory issues.

This reflects the index.dmh branch as of this morning.

This one appears in many, many cases. Fixing it will solve most of the ASAN issues in tests, I suspect. Here's an example from nctest:
```
ed@mikado:~/tmp/netcdf-c/nctest$ ./nctest 
Testing V2 API with 5 different netCDF formats.
Testing classic with file nctest_classic.nc.
*** Testing nccreate ...	ok ***
*** Testing ncopen ...		ok ***
*** Testing ncredef ...		ok ***
*** Testing ncendef ...		ok ***
*** Testing ncclose ...		ok ***
*** Testing ncinquire ...	ok ***
*** Testing ncsync ...		ok ***
*** Testing ncabort ...		ok ***
*** Testing ncdimdef ...	ok ***
*** Testing ncdimid ...		ok ***
*** Testing ncdiminq ...	ok ***
*** Testing ncdimrename ...	ok ***
*** Testing ncvardef ...	ok ***
*** Testing ncvarid ...		ok ***
*** Testing ncvarinq ...	ok ***
*** Testing ncvarputg ...	ok ***
*** Testing ncvarput1 ...	ok ***
*** Testing ncvarget1 ...	ok ***
*** Testing ncvarput ...	ok ***
*** Testing ncvarget ...	ok ***
*** Testing ncvarputg ...	ok ***
*** Testing ncvargetg ...	ok ***
*** Testing ncrecinq ...	ok ***
*** Testing ncrecput ...	ok ***
*** Testing ncrecget ...	ok ***
*** Testing ncvarrename ...	ok ***
*** Testing ncattput ...	ok ***
*** Testing ncattinq ...	ok ***
*** Testing ncattget ...	ok ***
*** Testing ncattcopy ...	ok ***
*** Testing ncattname ...	ok ***
*** Testing ncattrename ...	ok ***
*** Testing ncattdel ...	ok ***
*** Testing nctypelen ...	ok ***
Testing 64bit_offset with file nctest_64bit_offset.nc.
*** Testing nccreate ...	ok ***
*** Testing ncopen ...		ok ***
*** Testing ncredef ...		ok ***
*** Testing ncendef ...		ok ***
*** Testing ncclose ...		ok ***
*** Testing ncinquire ...	ok ***
*** Testing ncsync ...		ok ***
*** Testing ncabort ...		ok ***
*** Testing ncdimdef ...	ok ***
*** Testing ncdimid ...		ok ***
*** Testing ncdiminq ...	ok ***
*** Testing ncdimrename ...	ok ***
*** Testing ncvardef ...	ok ***
*** Testing ncvarid ...		ok ***
*** Testing ncvarinq ...	ok ***
*** Testing ncvarputg ...	ok ***
*** Testing ncvarput1 ...	ok ***
*** Testing ncvarget1 ...	ok ***
*** Testing ncvarput ...	ok ***
*** Testing ncvarget ...	ok ***
*** Testing ncvarputg ...	ok ***
*** Testing ncvargetg ...	ok ***
*** Testing ncrecinq ...	ok ***
*** Testing ncrecput ...	ok ***
*** Testing ncrecget ...	ok ***
*** Testing ncvarrename ...	ok ***
*** Testing ncattput ...	ok ***
*** Testing ncattinq ...	ok ***
*** Testing ncattget ...	ok ***
*** Testing ncattcopy ...	ok ***
*** Testing ncattname ...	ok ***
*** Testing ncattrename ...	ok ***
*** Testing ncattdel ...	ok ***
*** Testing nctypelen ...	ok ***
Testing netcdf4_classic with file nctest_netcdf4_classic.nc.
*** Testing nccreate ...	ok ***
*** Testing ncopen ...		ok ***
*** Testing ncredef ...		=================================================================
==23397==ERROR: AddressSanitizer: global-buffer-overflow on address 0x55ab735800a4 at pc 0x7fbecc522733 bp 0x7ffebb5976e0 sp 0x7ffebb596e88
READ of size 256 at 0x55ab735800a4 thread T0
    #0 0x7fbecc522732  (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x79732)
    #1 0x55ab7353b482 in NC4_def_var /home/ed/tmp/netcdf-c/libsrc4/nc4var.c:511
    #2 0x55ab734647be in nc_def_var /home/ed/tmp/netcdf-c/libdispatch/dvar.c:218
    #3 0x55ab73452e23 in ncvardef /home/ed/tmp/netcdf-c/libdispatch/dv2i.c:865
    #4 0x55ab734333a0 in test_ncredef /home/ed/tmp/netcdf-c/nctest/cdftests.c:279
    #5 0x55ab734380bf in main /home/ed/tmp/netcdf-c/nctest/driver.c:89
    #6 0x7fbecb0bf1c0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x211c0)
    #7 0x55ab73427fd9 in _start (/home/ed/tmp/netcdf-c/nctest/nctest+0x2efd9)

0x55ab735800a4 is located 0 bytes to the right of global variable '*.LC4' defined in 'nc4type.c' (0x55ab735800a0) of size 4
  '*.LC4' is ascii string 'int'
0x55ab735800a4 is located 60 bytes to the left of global variable '*.LC5' defined in 'nc4type.c' (0x55ab735800e0) of size 6
  '*.LC5' is ascii string 'float'
SUMMARY: AddressSanitizer: global-buffer-overflow (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x79732) 
Shadow bytes around the buggy address:
  0x0ab5ee6a7fc0: f9 f9 f9 f9 00 00 00 00 01 f9 f9 f9 f9 f9 f9 f9
  0x0ab5ee6a7fd0: 00 00 05 f9 f9 f9 f9 f9 00 00 00 00 00 00 00 00
  0x0ab5ee6a7fe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ab5ee6a7ff0: 00 00 00 00 05 f9 f9 f9 f9 f9 f9 f9 05 f9 f9 f9
  0x0ab5ee6a8000: f9 f9 f9 f9 05 f9 f9 f9 f9 f9 f9 f9 06 f9 f9 f9
=>0x0ab5ee6a8010: f9 f9 f9 f9[04]f9 f9 f9 f9 f9 f9 f9 06 f9 f9 f9
  0x0ab5ee6a8020: f9 f9 f9 f9 07 f9 f9 f9 f9 f9 f9 f9 06 f9 f9 f9
  0x0ab5ee6a8030: f9 f9 f9 f9 07 f9 f9 f9 f9 f9 f9 f9 05 f9 f9 f9
  0x0ab5ee6a8040: f9 f9 f9 f9 06 f9 f9 f9 f9 f9 f9 f9 07 f9 f9 f9
  0x0ab5ee6a8050: f9 f9 f9 f9 07 f9 f9 f9 f9 f9 f9 f9 00 00 00 00
  0x0ab5ee6a8060: 00 00 00 00 00 02 f9 f9 f9 f9 f9 f9 00 02 f9 f9
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==23397==ABORTING
```
Dennis you sent me some code to run under address sanitizer:
#include "config.h"
#include <stdlib.h>
#include <stdio.h>

#include "netcdf.h"

```
int
main()
{
    int ncid;
    int retval = NC_NOERR;
    int data[1] = {17};
    if(nc_create("tt.nc",NC_NETCDF4|NC_CLOBBER,&ncid))
    abort();
    if(nc_put_att(ncid,NC_GLOBAL, "att", NC_INT, 1, data))
    abort();
    if(nc_close(ncid))
    abort();
    return 0;
}
```

Here's the output from running it:

```
=================================================================
==30622==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 4 byte(s) in 1 object(s) allocated from:
    #0 0x7f37fa955538 in strdup (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x77538)
    #1 0x55e9929d6299 in nc4_att_list_add /home/ed/tmp/netcdf-c/libsrc4/nc4internal.c:968
    #2 0x55e9929a1eea in NC4_put_att /home/ed/tmp/netcdf-c/libsrc4/nc4attr.c:739
    #3 0x55e992917bf4 in nc_put_att /home/ed/tmp/netcdf-c/libdispatch/dattput.c:235
    #4 0x55e9929175ce in main /home/ed/tmp/netcdf-c/nc_test4/tst_types.c:15
    #5 0x7f37f94f41c0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x211c0)

SUMMARY: AddressSanitizer: 4 byte(s) leaked in 1 allocation(s).
```

**Comment by DennisHeimbigner** [comment]
ok, I finally solved the nc4_att_list_add problem. I was doing a double strdup
but so close together in time that I was missing that the address of the name changed.

**Comment by edhartnett** [comment]
What I find pretty amazing is that we find so few memory leaks (none, really) in the classic code. Yet it was written without the benefit if our modern memory checking tools.
